name: Hexo Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-18.04
    if: github.event.sender.id == "ymd45921"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo and gulp
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
          ACTION_SSH_CONFIG: ${{ secrets.HEXO_SSH_CONFIG }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          echo "$ACTION_SSH_CONFIG" > ~/.ssh/config
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan e.coding.net >> ~/.ssh/known_hosts
          git config --global user.email "ymd45921@163.com"
          git config --global user.name "Hexo Deploy BOT"
          git submodule init
          git submodule update
          npm install hexo-cli -g
          npm install gulp -g
          npm install

      - name: Build & Deploy
        run: |
          hexo clean
          hexo generate
          gulp
          hexo deploy
